export * from './Acoes';
export * from './ComunidadeService';
export * from './devocoesServices';
export * from './OracoesServices';
export * from './uploadImagemParoquia';
export * from './Palavra';
export * from './Publicacao';
export * from './sobreService';
export * from './UsuariosService';